### ISSUE TITLE
Replace Current GDSC Core Team Images with 2023 Team

### ISSUE THREAD

**Issue by 0xVikasRushi** [gdsccvr/GDSC-2021#2]
### 2. Create dropdown menu on Team which contains 2021 team and 2023 team 
<img width="1440" alt="Screenshot 2023-08-26 at 9 03 45 PM" src="https://github.com/gdsccvr/GDSC-2021/assets/88543171/2a33950d-3f20-4f6e-b727-337bb8658b9d">

**Comment by suraj719** [comment]
I will do it @0xVikasRushi

**Comment by c-shubh** [comment]
1. Replace [https://gdsccvr.vercel.app/team](https://github.com/gdsccvr/GDSC-2021/issues/gdsccvr) Images with current Images 

done in https://github.com/gdsccvr/GDSC-2021/pull/4

**Comment by 0xVikasRushi** [comment]
2. Create dropdown menu on Team which contains 2021 team and 2023 team
Completed #5
